server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: http://private-registry-service:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  jpa:
    database: H2
  datasource:
    url: jdbc:h2:mem:account
